import json
import re
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from app.config import settings


def _extract_json_payload(text_out: str) -> dict:
    cleaned = text_out.strip()

    # Handle markdown fenced responses such as ```json {...}```
    fence_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned, re.IGNORECASE)
    if fence_match:
        cleaned = fence_match.group(1).strip()

    # Try direct parse first
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # Try best-effort extraction of the first JSON object
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start != -1 and end != -1 and end > start:
        return json.loads(cleaned[start : end + 1])

    raise json.JSONDecodeError("No JSON object found", cleaned, 0)


def run_ai_audit(text: str, api_key: str) -> tuple[bool, float, str]:
    prompt = (
        "You are detecting whether a passage was likely generated by an LLM. "
        "Return strict JSON with keys: ai_detected (boolean), confidence (0-1 float), reasoning (string). "
        "Keep reasoning under 40 words.\n\n"
        f"TEXT:\n{text[:3000]}"
    )

    payload = {
        "model": settings.openai_model,
        "input": [{"role": "user", "content": [{"type": "input_text", "text": prompt}]}],
        "max_output_tokens": 180,
    }
    data = json.dumps(payload).encode("utf-8")

    request = Request(
        url=f"{settings.openai_base_url}/responses",
        data=data,
        method="POST",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )

    try:
        with urlopen(request, timeout=30) as response:
            raw = json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, TimeoutError) as exc:
        raise RuntimeError(f"OpenAI request failed: {exc}") from exc

    text_out = ""
    for item in raw.get("output", []):
        for content in item.get("content", []):
            if content.get("type") == "output_text":
                text_out += content.get("text", "")

    if not text_out.strip():
        raise RuntimeError("OpenAI response did not contain output text")

    try:
        parsed = _extract_json_payload(text_out)
        ai_detected = bool(parsed["ai_detected"])
        confidence = float(parsed["confidence"])
        reasoning = str(parsed["reasoning"]).strip()
        confidence = max(0.0, min(confidence, 1.0))
        if not reasoning:
            reasoning = "Model provided no reasoning text."
        return ai_detected, round(confidence, 4), reasoning[:300]
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        fallback_reasoning = text_out.strip().replace("\n", " ")
        return False, 0.5, fallback_reasoning[:300]
